name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---- new step: system library for PyAudio ----
      - name: Install system libs for PyAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev
      # ----------------------------------------------

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: speech_translate
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- lightweight smoke test: just import the modules ---
      - name: Smoke test imports
        working-directory: speech_translate
        run: |
          python - <<'PY'
          import importlib, sys
          for m in ("asr", "translate", "tts", "main"):
              importlib.import_module(m)
          print("All modules imported OK")
          PY
